"""Accepted pixel truth per registered scenario, committed to the repo.

`AGENTS.md` requires comparing a visual change against "the prior accepted
SHA" — this file is where that acceptance durably lives. `viz-baselines.toml`
at the checkout root maps every registered scenario to one pixel digest per
display track. `baseline check` re-renders each scenario with its default
controls and fails naming any scenario whose pixels drifted, any scenario
missing a baseline, and any stale entry for a scenario that no longer exists.
A pull request that changes pixels must update the baseline in the same diff,
which makes the PR itself the visual changelog.

The digest deliberately covers pixel content — fps, frame count, and raw RGB
bytes — rather than the artifact id. Artifact ids also hash the normalized
request and tool source files, so they churn when the toolchain changes even
though the pixels did not; a baseline should fail only when what the panel
would show changed.
"""

from __future__ import annotations

import hashlib
import tomllib
from pathlib import Path

from .models import RenderedSegment

BASELINE_FILE = "viz-baselines.toml"

_HEADER = """\
# viz-baselines.toml — the accepted pixel truth for every registered
# visualizer scenario, rendered with its default controls.
#
# Each digest covers fps, frame count, and exact RGB bytes for one display
# track. `uv run busybar-viz baseline check --json` fails when pixels drift
# from these values, when a registered scenario has no baseline, or when an
# entry goes stale. After deliberately changing a visual, inspect the fresh
# artifact, then accept it with `uv run busybar-viz baseline update` and
# commit this file in the same pull request as the change.
#
# Generated by `busybar-viz baseline update`; do not edit digests by hand.
"""


def pixel_digests(segment: RenderedSegment) -> dict[str, str]:
    """One content digest per display track: fps, frame count, exact bytes."""

    digests: dict[str, str] = {}
    for track in segment.displays:
        digest = hashlib.sha256()
        digest.update(f"{track.fps}:{len(track.frames)}:".encode("ascii"))
        for frame in track.frames:
            digest.update(frame.tobytes())
        digests[track.id] = digest.hexdigest()
    return digests


def load_baselines(repo_root: Path) -> dict[str, dict[str, str]]:
    """Read the committed baseline table; absent file means no baselines yet."""

    path = repo_root / BASELINE_FILE
    if not path.is_file():
        return {}
    document = tomllib.loads(path.read_text(encoding="utf-8"))
    baselines: dict[str, dict[str, str]] = {}
    for scenario_id, tracks in document.items():
        if not isinstance(tracks, dict) or not tracks or any(
            not isinstance(display, str) or not isinstance(digest, str)
            for display, digest in tracks.items()
        ):
            raise ValueError(
                f"{BASELINE_FILE}: {scenario_id!r} must map display ids to "
                "digest strings"
            )
        baselines[scenario_id] = dict(tracks)
    return baselines


def write_baselines(
    repo_root: Path,
    baselines: dict[str, dict[str, str]],
) -> Path:
    """Rewrite the baseline file deterministically, keeping its header."""

    lines = [_HEADER]
    for scenario_id in sorted(baselines):
        lines.append(f'["{scenario_id}"]')
        for display in sorted(baselines[scenario_id]):
            lines.append(f'{display} = "{baselines[scenario_id][display]}"')
        lines.append("")
    path = repo_root / BASELINE_FILE
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def compare_baselines(
    accepted: dict[str, dict[str, str]],
    rendered: dict[str, dict[str, str]],
) -> dict[str, object]:
    """Diff accepted baselines against freshly rendered digests."""

    changed = {
        scenario_id: {
            "accepted": accepted[scenario_id],
            "rendered": rendered[scenario_id],
        }
        for scenario_id in sorted(set(accepted) & set(rendered))
        if accepted[scenario_id] != rendered[scenario_id]
    }
    missing = sorted(set(rendered) - set(accepted))
    stale = sorted(set(accepted) - set(rendered))
    return {
        "ok": not changed and not missing and not stale,
        "checked": len(rendered),
        "changed": changed,
        "missing_baselines": missing,
        "stale_baselines": stale,
    }
