"""Safe source scaffolding for an explicitly registered viz adapter.

The generated adapter has one narrow contract: call a named, pure production
renderer returning ordinary PIL frames and wrap those values in viz-owned
types.  Production apps never import ``busybar_viz``.  The scaffold never
discovers Python from request data, and this module deliberately does not edit
the closed registry on the caller's behalf.
"""

from __future__ import annotations

import keyword
import re
import textwrap
from dataclasses import dataclass
from pathlib import Path
from types import MappingProxyType
from typing import Mapping

_ADAPTER_ID = re.compile(r"[a-z][a-z0-9_]{0,47}\Z")
_SCENARIO_NAME = re.compile(r"[a-z][a-z0-9-]{0,47}\Z")
_DOTTED_MODULE = re.compile(
    r"[A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)*\Z"
)
_PYTHON_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]*\Z")
_DISPLAY_IDS = frozenset({"front", "back"})


class ScaffoldCollisionError(FileExistsError):
    """One or more scaffold targets already exist; nothing was written."""

    def __init__(self, paths: tuple[Path, ...]):
        self.paths = paths
        super().__init__(
            "refusing to overwrite scaffold targets: "
            + ", ".join(str(path) for path in paths)
        )


@dataclass(frozen=True, slots=True)
class AdapterScaffoldSpec:
    adapter_id: str
    renderer_module: str
    renderer_name: str
    scenario_name: str = "default"
    title: str = "Deterministic app preview"
    description: str = "Production-rendered visual scenario."
    expected_displays: tuple[str, ...] = ("front",)

    def __post_init__(self) -> None:
        if (
            not isinstance(self.adapter_id, str)
            or not _ADAPTER_ID.fullmatch(self.adapter_id)
            or keyword.iskeyword(self.adapter_id)
        ):
            raise ValueError(
                "adapter_id must be non-keyword lower snake case and at most "
                "48 characters"
            )
        if (
            not isinstance(self.scenario_name, str)
            or not _SCENARIO_NAME.fullmatch(self.scenario_name)
        ):
            raise ValueError(
                "scenario_name must be lower kebab case and at most 48 characters"
            )
        if (
            not isinstance(self.renderer_module, str)
            or not _DOTTED_MODULE.fullmatch(self.renderer_module)
            or any(keyword.iskeyword(part) for part in self.renderer_module.split("."))
        ):
            raise ValueError(
                "renderer_module must be an absolute dotted Python module "
                "without keyword components"
            )
        if (
            not isinstance(self.renderer_name, str)
            or not _PYTHON_NAME.fullmatch(self.renderer_name)
            or keyword.iskeyword(self.renderer_name)
        ):
            raise ValueError("renderer_name must be a non-keyword Python identifier")
        if (
            not isinstance(self.title, str)
            or not self.title.strip()
            or len(self.title) > 120
        ):
            raise ValueError("title must contain 1-120 characters")
        if (
            not isinstance(self.description, str)
            or not self.description.strip()
            or len(self.description) > 300
        ):
            raise ValueError("description must contain 1-300 characters")
        if (
            not isinstance(self.expected_displays, tuple)
            or not self.expected_displays
            or any(not isinstance(item, str) for item in self.expected_displays)
            or len(set(self.expected_displays)) != len(self.expected_displays)
            or not set(self.expected_displays) <= _DISPLAY_IDS
        ):
            raise ValueError(
                "expected_displays must be a non-empty unique subset of front/back"
            )

    @property
    def scenario_id(self) -> str:
        return f"{self.adapter_id}/{self.scenario_name}"

    @property
    def class_name(self) -> str:
        base = "".join(part.capitalize() for part in self.adapter_id.split("_"))
        return base + "Adapter"


@dataclass(frozen=True, slots=True)
class ScaffoldPlan:
    files: Mapping[Path, str]
    registry_import: str
    registry_constructor: str


@dataclass(frozen=True, slots=True)
class ScaffoldResult:
    created: tuple[Path, ...]
    next_steps: tuple[str, ...]


def _adapter_source(spec: AdapterScaffoldSpec) -> str:
    expected = repr(spec.expected_displays)
    return textwrap.dedent(
        f'''\
        """Viz adapter for {spec.adapter_id}; generated by busybar-viz scaffold."""

        from __future__ import annotations

        from collections.abc import Mapping, Sequence

        from PIL import Image

        from busybar_viz.limits import validate_timing
        from busybar_viz.models import (
            CheckSpec,
            Confidence,
            DisplayTrack,
            EvidenceLevel,
            RenderedSegment,
            RenderRequest,
            ScenarioSpec,
        )
        from busybar_viz.profiles import profile_for

        _EXPECTED_DISPLAYS = {expected}


        def _render_production():
            # This static, lazy import keeps registry discovery side-effect free.
            # It returns {{display_id: (sequence_of_PIL_frames, fps)}} so the
            # production app never imports visualizer models.
            from {spec.renderer_module} import {spec.renderer_name} as renderer

            return renderer()


        def _wrap_production(value: object) -> RenderedSegment:
            if not isinstance(value, Mapping):
                raise TypeError(
                    "the production renderer must return a display mapping"
                )
            actual = tuple(value)
            if set(actual) != set(_EXPECTED_DISPLAYS):
                raise ValueError(
                    f"expected display tracks {{_EXPECTED_DISPLAYS!r}}, got {{actual!r}}"
                )
            tracks = []
            checks = []
            for display_id in _EXPECTED_DISPLAYS:
                item = value[display_id]
                if (not isinstance(item, tuple) or len(item) != 2
                        or not isinstance(item[0], Sequence)):
                    raise TypeError(
                        "each display value must be (sequence_of_frames, fps)"
                    )
                raw_frames, fps = item
                frames = tuple(raw_frames)
                if not frames or any(not isinstance(frame, Image.Image)
                                     for frame in frames):
                    raise TypeError("display frames must be non-empty PIL sequences")
                if any(frame.mode != "RGB" for frame in frames):
                    raise ValueError("production display frames must use RGB mode")
                validate_timing(frame_count=len(frames), fps=fps)
                expected_size = profile_for(display_id).size
                if any(frame.size != expected_size for frame in frames):
                    raise ValueError(
                        f"display track {{display_id!r}} must contain "
                        f"{{expected_size[0]}}x{{expected_size[1]}} frames"
                    )
                tracks.append(DisplayTrack(
                    display_id,
                    tuple(frame.copy() for frame in frames),
                    fps,
                    Confidence.SOURCE_EXACT,
                ))
                checks.append(CheckSpec.create(
                    f"{{display_id}}-dimensions",
                    "frame.dimensions",
                    display=display_id,
                    size=expected_size,
                ))
            return RenderedSegment(
                displays=tuple(tracks),
                evidence_level=EvidenceLevel.RENDERER_VERIFIED,
                checks=tuple(checks),
                source_paths=(
                    {str(Path(*spec.renderer_module.split('.')).with_suffix('.py'))!r},
                    {f'busybar_viz/adapters/{spec.adapter_id}.py'!r},
                ),
            )


        class {spec.class_name}:
            id = {spec.adapter_id!r}

            def scenarios(self) -> tuple[ScenarioSpec, ...]:
                return (ScenarioSpec(
                    {spec.scenario_id!r},
                    {spec.title!r},
                    {spec.description!r},
                    self.id,
                    expected_displays=_EXPECTED_DISPLAYS,
                ),)

            def render(self, request: RenderRequest) -> RenderedSegment:
                if request.scenario_id != {spec.scenario_id!r}:
                    raise KeyError(f"unknown {spec.adapter_id} scenario: {{request.scenario_id}}")
                if request.parameters or request.inputs:
                    raise ValueError(
                        "the generated scenario has no controls or inputs yet"
                    )
                return _wrap_production(_render_production())
        '''
    )


def _test_source(spec: AdapterScaffoldSpec) -> str:
    expected = repr(spec.expected_displays)
    return textwrap.dedent(
        f'''\
        """Contract checks for the {spec.adapter_id} visualizer seam."""

        from pathlib import Path

        from busybar_viz.artifacts import ArtifactStore
        from busybar_viz.adapters.{spec.adapter_id} import {spec.class_name}
        from busybar_viz.models import Confidence, RenderRequest
        from busybar_viz.offline import offline_render
        from busybar_viz.profiles import profile_for

        REPO = Path(__file__).resolve().parents[1]


        def test_{spec.adapter_id}_scenario_is_explicit_and_app_owned():
            spec = {spec.class_name}().scenarios()[0]

            assert spec.id == {spec.scenario_id!r}
            assert spec.adapter == {spec.adapter_id!r}
            assert spec.expected_displays == {expected}


        def test_{spec.adapter_id}_production_renderer_satisfies_the_track_contract(
            tmp_path,
        ):
            request = RenderRequest.from_values({spec.scenario_id!r})
            adapter = {spec.class_name}()
            with offline_render(REPO):
                segment = adapter.render(request)
                repeated = adapter.render(request)

            assert tuple(track.id for track in segment.displays) == {expected}
            for track in segment.displays:
                assert track.frames
                assert track.confidence is Confidence.SOURCE_EXACT
                assert all(frame.mode == "RGB" for frame in track.frames)
                assert all(frame.size == profile_for(track.id).size
                           for frame in track.frames)

            def exact_tracks(value):
                return tuple(
                    (track.id, track.fps, tuple(
                        frame.tobytes() for frame in track.frames
                    ))
                    for track in value.displays
                )

            assert exact_tracks(repeated) == exact_tracks(segment)
            artifact = ArtifactStore(tmp_path / "viz", REPO).publish(
                request, segment,
            )
            assert artifact.passed is True
        '''
    )


def plan_adapter_scaffold(spec: AdapterScaffoldSpec) -> ScaffoldPlan:
    """Return deterministic source without touching the checkout."""

    module_path = Path("busybar_viz") / "adapters" / f"{spec.adapter_id}.py"
    test_path = Path("tests") / f"test_viz_{spec.adapter_id}_adapter.py"
    files = MappingProxyType({
        module_path: _adapter_source(spec),
        test_path: _test_source(spec),
    })
    return ScaffoldPlan(
        files,
        f"from .adapters.{spec.adapter_id} import {spec.class_name}",
        f"{spec.class_name}()",
    )


def _target_path(repo_root: Path, relative: Path) -> Path:
    target = repo_root / relative
    try:
        target.parent.resolve(strict=True).relative_to(repo_root)
    except (FileNotFoundError, ValueError) as exc:
        raise ValueError(f"unsafe scaffold target: {relative}") from exc
    return target


def create_adapter_scaffold(
    repo_root: Path,
    spec: AdapterScaffoldSpec,
) -> ScaffoldResult:
    """Write a complete adapter/test pair, atomically with respect to collisions.

    Existing regular files, directories, and even broken symlinks are treated
    as collisions.  Registry editing remains an explicit reviewed step.
    """

    root = repo_root.resolve(strict=True)
    if (
        not (root / "busybar_viz" / "adapters").is_dir()
        or not (root / "tests").is_dir()
    ):
        raise ValueError("repo_root is not a BUSY Bar Lab checkout")
    plan = plan_adapter_scaffold(spec)
    targets = tuple(_target_path(root, relative) for relative in plan.files)
    collisions = tuple(
        target for target in targets if target.exists() or target.is_symlink()
    )
    if collisions:
        raise ScaffoldCollisionError(collisions)

    created: list[Path] = []
    try:
        for target, source in zip(targets, plan.files.values()):
            # Exclusive creation closes the preflight race without ever
            # truncating a user's file.
            with target.open("x", encoding="utf-8", newline="\n") as handle:
                created.append(target)
                handle.write(source)
    except BaseException:
        for target in reversed(created):
            target.unlink()
        raise

    return ScaffoldResult(
        tuple(created),
        (
            f"Add `{plan.registry_import}` to busybar_viz/registry.py.",
            f"Add `{plan.registry_constructor}` to the explicit adapters() tuple.",
            f"Run `uv run pytest -q tests/test_viz_{spec.adapter_id}_adapter.py`.",
        ),
    )
